# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DC', '0002_auto_20170901_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolarship',
            old_name='Level',
            new_name='level',
        ),
    ]
